-- Question 1:

WITH
	TOP_COUNTRIES AS (
		SELECT
			D.COUNTRY
		FROM
			CUSTOMER A
			INNER JOIN ADDRESS B ON A.ADDRESS_ID = B.ADDRESS_ID
			INNER JOIN CITY C ON B.CITY_ID = C.CITY_ID
			INNER JOIN COUNTRY D ON C.COUNTRY_ID = D.COUNTRY_ID
		GROUP BY
			D.COUNTRY
		ORDER BY
			COUNT(A.CUSTOMER_ID) DESC
		LIMIT
			10
	),
	TOP_CITIES AS 
	(SELECT
        C.CITY
    FROM
        CUSTOMER A
        INNER JOIN ADDRESS B ON A.ADDRESS_ID = B.ADDRESS_ID
        INNER JOIN CITY C ON B.CITY_ID = C.CITY_ID
        INNER JOIN COUNTRY D ON C.COUNTRY_ID = D.COUNTRY_ID
    WHERE
        D.COUNTRY IN (SELECT * FROM TOP_COUNTRIES)
    GROUP BY
		D.COUNTRY,
        C.CITY
    ORDER BY
        COUNT(A.CUSTOMER_ID) DESC
    LIMIT
        10
	 ),
	 TOP_CUSTOMERS AS (
	 SELECT
			SUM(A.AMOUNT) AS TOTAL_PAYMENT
		FROM
			PAYMENT A
			INNER JOIN CUSTOMER B ON A.CUSTOMER_ID = B.CUSTOMER_ID
			INNER JOIN ADDRESS C ON B.ADDRESS_ID = C.ADDRESS_ID
			INNER JOIN CITY D ON C.CITY_ID = D.CITY_ID
			INNER JOIN COUNTRY E ON D.COUNTRY_ID = E.COUNTRY_ID
		WHERE 
			D.CITY IN (SELECT * FROM TOP_CITIES)
			GROUP BY B.FIRST_NAME, B.LAST_NAME, D.CITY, E.COUNTRY
			ORDER BY TOTAL_PAYMENT DESC
			LIMIT 5
	 )
SELECT AVG(TOTAL_PAYMENT)
FROM TOP_CUSTOMERS

-- Question 2:

WITH
    TOP_COUNTRIES AS (
        SELECT
            D.COUNTRY
        FROM
            CUSTOMER A
            INNER JOIN ADDRESS B ON A.ADDRESS_ID = B.ADDRESS_ID
            INNER JOIN CITY C ON B.CITY_ID = C.CITY_ID
            INNER JOIN COUNTRY D ON C.COUNTRY_ID = D.COUNTRY_ID
        GROUP BY
            D.COUNTRY
        ORDER BY
            COUNT(A.CUSTOMER_ID) DESC
        LIMIT 10
    ),
    TOP_CITIES AS (
        SELECT
            C.CITY
        FROM
            CUSTOMER A
            INNER JOIN ADDRESS B ON A.ADDRESS_ID = B.ADDRESS_ID
            INNER JOIN CITY C ON B.CITY_ID = C.CITY_ID
            INNER JOIN COUNTRY D ON C.COUNTRY_ID = D.COUNTRY_ID
        WHERE
            D.COUNTRY IN (SELECT COUNTRY FROM TOP_COUNTRIES)
        GROUP BY
            C.CITY, D.COUNTRY
        ORDER BY
            COUNT(A.CUSTOMER_ID) DESC
        LIMIT 10
    ),
    TOP_CUSTOMERS AS (
        SELECT
            B.CUSTOMER_ID,
            SUM(A.AMOUNT) AS TOTAL_PAYMENT
        FROM
            PAYMENT A
            INNER JOIN CUSTOMER B ON A.CUSTOMER_ID = B.CUSTOMER_ID
            INNER JOIN ADDRESS C ON B.ADDRESS_ID = C.ADDRESS_ID
            INNER JOIN CITY D ON C.CITY_ID = D.CITY_ID
            INNER JOIN COUNTRY E ON D.COUNTRY_ID = E.COUNTRY_ID
        WHERE
            D.CITY IN (SELECT CITY FROM TOP_CITIES)
        GROUP BY
            B.CUSTOMER_ID
        ORDER BY
            TOTAL_PAYMENT DESC
        LIMIT 5
    )
SELECT
    D.COUNTRY,
    COUNT(DISTINCT A.CUSTOMER_ID) AS ALL_CUSTOMER_COUNT,
    COUNT(DISTINCT T.CUSTOMER_ID) AS TOP_CUSTOMER_COUNT
FROM
    CUSTOMER A
    INNER JOIN ADDRESS B ON A.ADDRESS_ID = B.ADDRESS_ID
    INNER JOIN CITY C ON B.CITY_ID = C.CITY_ID
    INNER JOIN COUNTRY D ON C.COUNTRY_ID = D.COUNTRY_ID
    LEFT JOIN TOP_CUSTOMERS T ON A.CUSTOMER_ID = T.CUSTOMER_ID
GROUP BY
    D.COUNTRY
ORDER BY
    TOP_CUSTOMER_COUNT DESC
LIMIT 10;
